name: csi-powerflex
version: 1.1.5
apiVersion: v2
appVersion: 1.1.5
icon: https://avatars1.githubusercontent.com/u/34447988
description: |
  VxFlex OS CSI (Container Storage Interface) driver Kubernetes
  integration. This chart includes everything required to provision via CSI as
  well as a VxFlex OS StorageClass.
keywords:
- csi
- storage
sources:
- https://github.com/dell/csi-powerflex
maintainers:
- name: DellEMC
engine: gotpl
